name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build with Docker Compose
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🔧 Configura o Docker Buildx (permite build multi-plataforma e cache)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 🧱 Construção da imagem com docker-compose
      - name: Build Docker Compose services
        run: |
          docker compose -f docker-compose.yml build
